### ISSUE TITLE
Failed to decode stamp error on valid stamp

### ISSUE THREAD

**Issue by user8446** [instantsc/SimpleDnsCrypt#1]
Hello,

After entering a valid DNS stamp, a "Failed to decode stamp" error appears. The DNS stamp is correct and even verified on https://dnscrypt.info/stamps
Any thoughts?

**Comment by instantsc** [comment]
I've made a new release that should improve the validation errors: https://github.com/instantsc/SimpleDnsCrypt/releases/tag/0.7.2.3. If this reoccurs, please at least provide the stamp you're trying to use.

**Comment by user8446** [comment]
Thank you for the update! I'll reopen if there are any issues. I'm using NextDNS though and wouldn't be able to post the stamp because it has my private server name/path in it.
