### ISSUE TITLE
DNSCryptProxy 2.1.4

### ISSUE THREAD

**Issue by G33w1z** [instantsc/SimpleDnsCrypt#10]
DNSCryptProxy 2.1.4 has been released. The good news is I've tested replacing dnscrypt-proxy64.exe and dnscrypt-proxy86.exe in the \SimpleDNSCrypt\dnscrypt-proxy folder, restarting the service, and all is working well. Passes dnsleaktest.com without leaking to my ISP's resolver.

**Comment by instantsc** [comment]
Updated in 0.8.1
