### ISSUE TITLE
[0.8.1] Long IP address hint

### ISSUE THREAD

**Issue by iDolmatov** [instantsc/SimpleDnsCrypt#11]
![2023-03-14 02 01 16](https://user-images.githubusercontent.com/19782385/224831939-fdd0f56f-5fa7-4b59-be5a-6a3c41bf1952.png)

Due to IPv6, the new feature displays a long tooltip.
It is possible to make transfer of lines on each IP.

Consider replacing this with an (i) info button. There are child windows in other places, so there shouldn't be any problems with the implementation.
This will display other data, as if we were using "arp -a" and "ipconfig /all" requests.

**Comment by instantsc** [comment]
Oh I haven't considered that there's network setup that have a *lot* of addresses assigned. I'll see what I can do. I don't want to turn the feature into the "view network config" though, there are better tools for that and the IP display was meant to help recognize the correct network at a glance. If you have suggestions about what other data might help there, please let me know.

**Comment by iDolmatov** [comment]
I do not have many network connections, once upon a time saw this. 
I can roughly imagine why this is needed, but usually you know the necessary connections by their names.

If a quick display of the IP address is required, then I will try to suggest an optimization.

- Do not overlap the checkmark icon after the IP address. It should be left-aligned, indented from the right edge by the width of the icon.
![2023-03-14 03 25 13](https://user-images.githubusercontent.com/19782385/224846315-3bd1f1f1-4956-4950-91c9-30690533e638.png)

- Write the first IP address of any version. If you have multiple IPs (including multiple IPv4/6 from OS settings), put a comma and an ellipsis. Increase the width of the green field, as you do with long network connection names.
- I don't think it's necessary to display ALL addresses in the tooltip. If there are no IP conflicts in the system and the user knows the addresses, then 1-2 addresses will be enough for him.
Make a two-line hint - one line per IP version. Show 1-2 IPs per version, and abbreviate the third one with an ellipsis. 
A large hint from many IPs also complicates the use, so it is useful to shorten it. If there is a request for more data, then this can be implemented with the "Show all IP addresses" switch. Now I do not see the need to complicate the program code.


P.S. You can think more about the UI of the network card selection button and hints. I based on what I wrote earlier. The idea of displaying all IPs in a long column seemed short-sighted. I'm not even sure what the limit of alternative configurations is. The Windows interface allows you to set several configurations through an additional dialog box.

**Comment by iDolmatov** [comment]
Additional solution for long strings. Switch between table view and icon view. In the usual form, show a minimum of data. In tabular form, output as strings without displaying a tooltip. Only very long lines (wider than the program window) will require a line break, which will increase the "line height" in some cases.

The nuance is in the complication of the UI in terms of code (different layers with visibility and activity settings), thinking through scrolling and placing the icons "WiFi", "LAN", "Other" at the beginning (at the end).

**Comment by instantsc** [comment]
I've cleaned up the markup to prevent possible issues and trimmed the possible large tooltips. For now, I consider this issue solved, I do not plan any huge refactoring of visuals anytime soon.
