### ISSUE TITLE
update dnscrypt-proxy 2.1.5?

### ISSUE THREAD

**Issue by rigaz29** [instantsc/SimpleDnsCrypt#12]

**Comment by LeonMskRu** [comment]
manual replace .exe (stop service need) worked
https://github.com/DNSCrypt/dnscrypt-proxy/releases
C:\Program Files\SimpleDNSCrypt\dnscrypt-proxy>                                                                                                                                    
11.08.2023  16:59         8 927 232 dnscrypt-proxy64.exe (**new 2.1.5**)
12.03.2023  16:37         8 810 496 dnscrypt-proxy86.exe

**Comment by instantsc** [comment]
Done in 0.8.2
