### ISSUE TITLE
Virus Total result false positive ??

### ISSUE THREAD

**Issue by TecnikOfficial** [instantsc/SimpleDnsCrypt#15]
SimpleDnsCrypt ( forked instantsc version) -- [virus total result](https://www.virustotal.com/gui/file/ca2ae4a08cb38b1915244767659e0383beb3b9b307c57dfb6fba7b1f91e66a17?nocache=1)
SimpleDnsCrypt ( original version) -- [virus total result](https://www.virustotal.com/gui/file/5ba0c94774acd7ade18446b4351e7d28a948c490aefc50dc6c08c13551f19f7f/detection)

**Comment by instantsc** [comment]
Yeah, not paying a fee (called a "code signing certificate") gets you called "malware" by all kinds of irrelevant "security" products. Feel free to inspect the code and the build pipeline, it's all automated.
