### ISSUE TITLE
domain blacklist is not working [DNS cache is not cleared on blocklist update]

### ISSUE THREAD

**Issue by aphelion1** [instantsc/SimpleDnsCrypt#2]
i was testing block domain list with simplednscrypt but it didn't worked, i used "wildcard" and "domains" from here:
`https://www.reddit.com/r/dnscrypt/comments/s4q096/adult_blocklist_myprivacydnss_pornrecords/`
am i doing something wrong or the app can't use this feature yet?

**Comment by aphelion1** [comment]
i tested again,it's working, maybe a button to delete the dns cache could be useful

**Comment by instantsc** [comment]
Added purge on settings change in https://github.com/instantsc/SimpleDnsCrypt/releases/tag/0.7.2.4, please check if it solves your issues.

**Comment by aphelion1** [comment]
it works better but i need to close all tabs on incognito , without closing all tabs on incognito mode it doesn't work, i am testing on incognito mode

**Comment by instantsc** [comment]
This means then that your browser's incognito mode uses some other form of dns caching (which makes sense for privacy, but is unfortunate here).

**Comment by aphelion1** [comment]
i tested on all browsers that i have installed chrome, chromium, firefox, on firefox i have dns cache disabled, it seems on chromium it's disabled by default, i am using ublock origin just that extension
