### ISSUE TITLE
Servers and Relays

### ISSUE THREAD

**Issue by Cosmoufle** [instantsc/SimpleDnsCrypt#3]
Hello,

I found that dnscrypt-proxy.toml is using old **v2** adresses for dnscrypt-proxy that was used till v2.0.42:
example:
https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/ **v2** /public-resolvers.md

instead for the further versions the new **v3** for all adresses

https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/ **v3** /public-resolvers.md

------
An option could be added to enable "odoh" servers that have been added after v2.0.42

Thanks for the nice work!

**Comment by instantsc** [comment]
I'll look into it at some point

**Comment by instantsc** [comment]
Done in https://github.com/instantsc/SimpleDnsCrypt/releases/tag/0.8.0
