### ISSUE TITLE
Installed this version and it still shows version 2.0.42

### ISSUE THREAD

**Issue by jamesta696** [instantsc/SimpleDnsCrypt#4]
Hi, 
after installing the latest from this section, when I open Simple DNSCrypt, it still shows it's using version 2.0.42 and does not have any of the latest features shown in the main readme section of repo.

Can you please help me install the latest version?

Im running:

**Windows 10 (64bit)
Version: 21H1
OS Build: 19043.1466
Experience: Windows Feature Experience Pack 120.2212.3920.0**

Thanks

**Comment by instantsc** [comment]
You probably just didn't uninstall the bitbeans version manually, so windows search is still showing its entries from the start menu.
My version does not interact with the bitbeans one in any way (except overriding their service with ours if you uninstall and then install service from my version's UI).
Try uninstalling the bitbeans version first.

**Comment by jamesta696** [comment]
Thanks for your feedback @instantsc !
It seems even when I uninstalled the bitbeans version, it left some files behind hidden somewhere, I had to perform system restore to before I installed Simple DNSCrypt and then I installed this version and it's showing it's updated now.

Thanks again and keep up the good work!
