### ISSUE TITLE
Not an issue, just a help request: IPs?

### ISSUE THREAD

**Issue by EstherMoellman** [instantsc/SimpleDnsCrypt#5]
Hi @instantsc ,

Thank you for your SimpleDnsCryp version... very useful!

Please, I have a simple question: How can I block IPs?
By following the regular DNSCryp Wiki, and using your SimpleDnsCrypt 0.7.2.4, I edited my dnscrypt-proxy.toml by adding:

**[blocked_ips]
blocked_names_file = "C:\\Program Files\\SimpleDNSCrypt\\dnscrypt-proxy\\IPblacklist.txt"**

... where IPblacklist.txt is a file containing my IPs blocked list.
Unfortunately is not working for me.

Please, can you help me?

Thank you in advance.

**Comment by TroudhuK** [comment]
blocked_ips => blocked_ips_file

**Comment by instantsc** [comment]
As mentioned above, your config key appears to be wrong, see example config here https://github.com/DNSCrypt/dnscrypt-proxy/blob/5f88a9146ca93c329a1b40c7bfde98c104884d4c/dnscrypt-proxy/example-dnscrypt-proxy.toml#L558
