### ISSUE TITLE
Resolvers list is hard to switch

### ISSUE THREAD

**Issue by Mishasama** [instantsc/SimpleDnsCrypt#9]
https://github.com/instantsc/SimpleDnsCrypt/releases/tag/0.8.0
![image](https://user-images.githubusercontent.com/54498172/205771842-f9827a38-86a4-4459-aa5c-c5b9490352f9.png)

The resolvers list is hard to switch. It needs a double click to change.

**Comment by instantsc** [comment]
Should be fixed now
